### ISSUE TITLE
Phylanx won't build with Clang 6.0 on OSX

### ISSUE THREAD

**Issue by khuck** [STEllAR-GROUP/phylanx#585]
Clang 6.0 is complaining that the difference_type is ambiguous.

```
[ 58%] Building CXX object src/plugins/matrixops/CMakeFiles/matrixops_primitive.dir/argmax.cpp.o
/Volumes/OmegaExternal/src/phylanx/src/plugins/matrixops/argmax.cpp:120:16: error: ambiguous conversion for
      functional-style cast from 'typename iterator_traits<DenseIterator<double, true> >::difference_type'
      (aka 'long') to 'phylanx::execution_tree::primitive_argument_type'
        return primitive_argument_type(std::distance(a.begin(), max_it));
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Volumes/OmegaExternal/src/phylanx/phylanx/execution_tree/primitives/primitive_argument_type.hpp:201:18: note: 
      candidate constructor
        explicit primitive_argument_type(bool val)
                 ^
/Volumes/OmegaExternal/src/phylanx/phylanx/execution_tree/primitives/primitive_argument_type.hpp:204:18: note: 
      candidate constructor
        explicit primitive_argument_type(std::uint8_t val)
                 ^
/Volumes/OmegaExternal/src/phylanx/phylanx/execution_tree/primitives/primitive_argument_type.hpp:229:18: note: 
      candidate constructor
        explicit primitive_argument_type(std::int64_t val)
                 ^
/Volumes/OmegaExternal/src/phylanx/phylanx/execution_tree/primitives/primitive_argument_type.hpp:272:18: note: 
      candidate constructor
        explicit primitive_argument_type(double val)
                 ^
/Volumes/OmegaExternal/src/phylanx/phylanx/execution_tree/primitives/primitive_argument_type.hpp:324:9: note: 
      candidate constructor
        primitive_argument_type(ir::range&& val)
        ^
/Volumes/OmegaExternal/src/phylanx/phylanx/execution_tree/primitives/primitive_argument_type.hpp:321:9: note: 
      candidate constructor
        primitive_argument_type(ir::range const& val)
        ^
/Volumes/OmegaExternal/src/phylanx/phylanx/execution_tree/primitives/primitive_argument_type.hpp:338:9: note: 
      candidate constructor
        primitive_argument_type(argument_value_type&& val)
        ^
/Volumes/OmegaExternal/src/phylanx/phylanx/execution_tree/primitives/primitive_argument_type.hpp:335:9: note: 
      candidate constructor
        primitive_argument_type(argument_value_type const& val)
        ^
1 error generated.
make[2]: *** [src/plugins/matrixops/CMakeFiles/matrixops_primitive.dir/argmax.cpp.o] Error 1
make[1]: *** [src/plugins/matrixops/CMakeFiles/matrixops_primitive.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by khuck** [comment]
Yes it does.  Making a pull request now...
